# Anel Amanbekova, SE2011

# KNN 

In [134]:
# library for math operations on numerical data
import numpy as np
# library for operations on tabular data
import pandas as pd
# library for data analysis
from sklearn import tree
# import to split the data into test sets
from sklearn.model_selection import train_test_split
# import to standartize the data into standart format
from sklearn.preprocessing import StandardScaler
# for KNN
from sklearn.neighbors import KNeighborsClassifier
# import to define problems in classification algorithm 
from sklearn.metrics import confusion_matrix
# import to compute F1 score
from sklearn.metrics import f1_score
# for Decision Tree
from sklearn.tree import DecisionTreeClassifier
# for Random Forest
from sklearn.ensemble import RandomForestClassifier
# import to calculate the accuracy
from sklearn.metrics import accuracy_score

In [135]:
# read csv file 
df = pd.read_csv("drug200.csv")
# get first 10 record from dataset
df.head(10)

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY
5   22   F  NORMAL        HIGH    8.607  drugX
6   49   F  NORMAL        HIGH   16.275  DrugY
7   41   M     LOW        HIGH   11.037  drugC
8   60   M  NORMAL        HIGH   15.171  DrugY
9   43   M     LOW      NORMAL   19.368  DrugY

In [136]:
# get lenght of dataset
len(df)

200

In [137]:
# replace all words to numerical data

# label Females and Males as 1 or 0
df=df.replace(to_replace="F",value="1")
df=df.replace(to_replace="M",value="0")
# label BP as 0-2 and cholesterol as 1 or 0
df=df.replace(to_replace="HIGH",value="0")
df=df.replace(to_replace="NORMAL",value="1")
df=df.replace(to_replace="LOW",value="2")

In [138]:
df.head(10)

Age Sex BP Cholesterol  Na_to_K   Drug
0   23   1  0           0   25.355  DrugY
1   47   0  2           0   13.093  drugC
2   47   0  2           0   10.114  drugC
3   28   1  1           0    7.798  drugX
4   61   1  2           0   18.043  DrugY
5   22   1  1           0    8.607  drugX
6   49   1  1           0   16.275  DrugY
7   41   0  2           0   11.037  drugC
8   60   0  1           0   15.171  DrugY
9   43   0  2           1   19.368  DrugY

In [139]:
# splitting the dataset
# iloc to select specific row/columns from the data

# use only training part of the data
# which are all rows and all columns except 6th column (cause this is the answer column)
X = df.iloc[:, 0:5]
#only answers
y = df.iloc[:, 5]
# test_size = 0.2 means 80% training and 20% of test from the data
# random_state controls the shuffling process
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size=0.2)

In [140]:
# Feature scaling
# we scale the data to standartize it (mean = 0 and standart deviation = 1)
sc_X = StandardScaler()
#scale train and test data
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [141]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

160
160
40
40


In [142]:
# import library to use math operations
import math
#calculate the value of K which is square root of all values 
math.sqrt(len(df))

14.142135623730951

In [143]:
# Define the model: KNN
#since we have 3 types of answers it is okay to use even value of K
classifier = KNeighborsClassifier(n_neighbors = 14, metric='euclidean')

In [144]:
# Fit model of KNN with our data
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=14)

In [145]:
# Predict the test set results
y_pred = classifier.predict(X_test)
y_pred

array(['drugC', 'drugA', 'DrugY', 'DrugY', 'DrugY', 'drugX', 'drugX',
       'drugX', 'DrugY', 'drugX', 'drugA', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'drugC', 'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'drugB', 'drugX', 'drugX', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'DrugY', 'drugX', 'drugX', 'drugC', 'drugA', 'drugX', 'DrugY',
       'DrugY', 'drugX', 'DrugY', 'DrugY', 'DrugY'], dtype=object)

In [146]:
X_test

array([[-1.32743718, -0.93933644,  1.30088727, -0.92761259, -1.22346977],
       [-1.02626028,  1.06458129,  0.11826248, -0.92761259, -0.44626402],
       [-0.18296497, -0.93933644,  1.30088727, -0.92761259,  0.5472113 ],
       [-1.50814332, -0.93933644, -1.06436231,  1.07803625,  2.72327597],
       [-1.20696642, -0.93933644,  0.11826248, -0.92761259,  0.40767355],
       [-1.50814332,  1.06458129,  1.30088727,  1.07803625, -0.61240028],
       [-1.38767256,  1.06458129,  0.11826248, -0.92761259, -1.04117944],
       [-0.48414186,  1.06458129,  1.30088727,  1.07803625, -0.56783733],
       [-0.12272959, -0.93933644,  1.30088727, -0.92761259, -0.09853374],
       [ 0.60009497, -0.93933644,  0.11826248,  1.07803625, -1.22862236],
       [-1.2672018 , -0.93933644, -1.06436231,  1.07803625, -0.92030243],
       [-1.5683787 ,  1.06458129, -1.06436231,  1.07803625,  1.37663925],
       [-1.38767256,  1.06458129, -1.06436231,  1.07803625,  0.93783343],
       [-0.48414186, -0.93933644,  1.3

In [147]:
# Evaluate model to the confusion matrix
# Compute confusion matrix to evaluate the accuracy of a classification
cm = confusion_matrix(y_test, y_pred)
print (cm)

[[17  0  0  0  2]
 [ 1  2  0  0  0]
 [ 1  0  0  0  0]
 [ 0  0  0  3  0]
 [ 1  1  1  0 11]]


In [148]:
# find accuracy by comparing test set and predicted set
print(accuracy_score(y_test, y_pred))

0.825


Next step is to test data with different test_size from 0.2 to 0.3 {0.20, 0.21, 0.22, 0.23, ..., 0.30}

In [158]:
# for every test_size from 0.2 to 0.3 with step of 0.01
# find accuracy
KNNAccuracy = []
for i in np.arange(0.2, 0.31, 0.01):
    X = df.iloc[:, 0:5]
    y = df.iloc[:, 5]
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size=i)
    sc_X = StandardScaler()
    X_train = sc_X.fit_transform(X_train)
    X_test = sc_X.transform(X_test)
    classifier = KNeighborsClassifier(n_neighbors=14, metric='euclidean')
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    KNNAccuracy.append(accuracy_score(y_test, y_pred))

In [159]:
KNNAccuracy

[0.825,
 0.8372093023255814,
 0.8444444444444444,
 0.8723404255319149,
 0.8367346938775511,
 0.7647058823529411,
 0.7735849056603774,
 0.7636363636363637,
 0.7719298245614035,
 0.7457627118644068,
 0.7377049180327869]

# Decision Tree

In [160]:
X = df.iloc[:, 0:5]
y = df.iloc[:, 5]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size = 0.2)

In [164]:
# function to perform training with entropy
# max_depth is the maximum depth of the tree. If None, then nodes are expanded until all leaves are pure
# min_samples_leaf is the minimum number of samples required to be at a leaf node
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 0, max_depth = 3, min_samples_leaf = 5)
# fit our train data into DT model
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=0)

In [165]:
# predict answer set and print it
y_pred_en = clf_entropy.predict(X_test)
y_pred_en

array(['drugC', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugC', 'drugX',
       'drugC', 'DrugY', 'drugX', 'drugA', 'DrugY', 'DrugY', 'DrugY',
       'drugB', 'drugC', 'DrugY', 'DrugY', 'drugC', 'DrugY', 'DrugY',
       'drugX', 'drugX', 'drugC', 'DrugY', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'drugX', 'drugC', 'drugC', 'drugA', 'drugX', 'DrugY',
       'DrugY', 'drugX', 'DrugY', 'drugA', 'drugX'], dtype=object)

In [166]:
# printing the accuracy
print (accuracy_score(y_test, y_pred_en))

0.875


In [169]:
DTAccuracy = []
for i in np.arange(0.2, 0.31, 0.01):
    X = df.iloc[:, 0:5]
    y = df.iloc[:, 5]
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size = i)
    clf_entropy = DecisionTreeClassifier(criterion = "entropy", max_depth = 3, min_samples_leaf = 5)
    clf_entropy.fit(X_train, y_train)
    y_pred_en = clf_entropy.predict(X_test)
    DTAccuracy.append(accuracy_score(y_test, y_pred_en))

In [170]:
DTAccuracy

[0.875,
 0.8837209302325582,
 0.8666666666666667,
 0.851063829787234,
 0.8571428571428571,
 0.8627450980392157,
 0.8679245283018868,
 0.8727272727272727,
 0.8771929824561403,
 0.8813559322033898,
 0.8852459016393442]

We can see that accuracy of Decision Tree model is higher that KNN.

# Random Forest

In [171]:
X = df.iloc[:, 0:5]
y = df.iloc[:, 5]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0, test_size=0.2)

In [172]:
# Create RF Classifier
# n_estimators is the number of trees in forest, by default it is 100
clf=RandomForestClassifier(n_estimators=100, max_depth = 3, min_samples_leaf = 5)
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

RandomForestClassifier(max_depth=3, min_samples_leaf=5)

In [173]:
# predict the answers
y_pred=clf.predict(X_test)

In [174]:
# calculate accuracy
accuracy_score(y_test, y_pred)

0.925

In [177]:
RFAccuracy = []
for i in np.arange(0.2, 0.31, 0.01):
    X = df.iloc[:, 0:5]
    y = df.iloc[:, 5]
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size = i)
    clf=RandomForestClassifier(n_estimators=100, random_state = 0, max_depth = 3, min_samples_leaf = 5)
    clf.fit(X_train,y_train)
    y_pred=clf.predict(X_test)
    RFAccuracy.append(accuracy_score(y_test, y_pred))

In [178]:
RFAccuracy

[0.925,
 0.9302325581395349,
 0.9333333333333333,
 0.9361702127659575,
 0.9387755102040817,
 0.9411764705882353,
 0.9433962264150944,
 0.9272727272727272,
 0.9298245614035088,
 0.9322033898305084,
 0.9344262295081968]

In [179]:
test_size_v = [0.2, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3]

In [180]:
data = {'test_size': test_size_v, 'KNN': KNNAccuracy, 'DT': DTAccuracy, 'RF': RFAccuracy}
accuracy_df = pd.DataFrame(data=data)

In [181]:
# table with all test_sizes and accuracy of all 3 models
accuracy_df

test_size       KNN        DT        RF
0        0.20  0.825000  0.875000  0.925000
1        0.21  0.837209  0.883721  0.930233
2        0.22  0.844444  0.866667  0.933333
3        0.23  0.872340  0.851064  0.936170
4        0.24  0.836735  0.857143  0.938776
5        0.25  0.764706  0.862745  0.941176
6        0.26  0.773585  0.867925  0.943396
7        0.27  0.763636  0.872727  0.927273
8        0.28  0.771930  0.877193  0.929825
9        0.29  0.745763  0.881356  0.932203
10       0.30  0.737705  0.885246  0.934426

In [198]:
# get max accuracy from each model
max_KNN = accuracy_df['KNN'].max(axis=0)
max_DT = accuracy_df['DT'].max(axis=0)
max_RF = accuracy_df['RF'].max(axis=0)

In [197]:
# function to highlight MAX values
def highlight_cells(val):
    color = 'red' if ((val == max_KNN) | (val == max_RF) | (val == max_DT)) else ''
    return 'background-color: {}'.format(color)

accuracy_df.style.applymap(highlight_cells)

  From this table we can observe that in general accuracy of KNN model is lower than DT and RF. Probable cause for that may be the fact that KNN does not have any training data, those accuracy is lower. Also it takes a lot of time to count destination in KNN, that's why it is not convenient to use this model with large datasets.
  Decision tree model's accuracy is higher than KNN. This is because we use part of the data for training, during this trainin DT gains knowlege about the data and it helps to make better predictions.
  Random Forest, as we can see, has the most accurate predictions. This is because Random Forest consist of multiple Decision Trees which are operating together and outperform any of the individual constituent models.
